import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/modalvote">ModalVote</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
        <li>
          <Link to="/landingpageafterlogin">LandingPageAfterLogin</Link>
        </li>
        <li>
          <Link to="/voteone">VoteOne</Link>
        </li>
        <li>
          <Link to="/detailpage">DetailPage</Link>
        </li>
        <li>
          <Link to="/detailpageafterlogin">DetailPageAfterLogin</Link>
        </li>
        <li>
          <Link to="/vote">Vote</Link>
        </li>
        <li>
          <Link to="/admin">Admin</Link>
        </li>
        <li>
          <Link to="/listpaslon">ListPaslon</Link>
        </li>
        <li>
          <Link to="/addpaslon">AddPaslon</Link>
        </li>
        <li>
          <Link to="/listpartai">ListPartai</Link>
        </li>
        <li>
          <Link to="/addpartai">AddPartai</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
